name: Estraier
id:   Estraier
key:  estraier
version: 0.2
author_link: http://alfasado.net/
author_name: Alfasado Inc.
description: Dynamic Handler for Search Estraier.
tags:
    block:
        EstraierSearch: $estraier::Estraier::Tags::_hdlr_estraier_search
    function:
        EstraierCount: $estraier::Estraier::Tags::_hdlr_estraier_count
